services:
  flask-app:
    container_name: python-escomio-app
    environment:
      - FLASK_ENV=docker
    build: .
    image: python-escomio:v1

  python-nginx-server:
    container_name: nginx-server
    build: ./nginx
    ports:
      - 5001:5001
    depends_on:
      - flask-app